baseURL = "https://moneyboth.com/"
languageCode = "en-us"
title = "Blog"
[pagination]
  pagerSize = 10

[params]
  author = "MoneyBoth"
  description = "A simple blog about money and smart thinking"
  github = "https://github.com/moneyboth/blog"
